name: Deploy to Heroku (and good luck to me)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Heroku CLI (official action)
      - name: Setup Heroku
        uses: heroku/actions/setup@v2

      # Log in to Heroku and its container registry
      - name: Heroku login
        run: heroku login --interactive <<< $'q' || true

      - name: Container registry login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      # Build your Docker image (tag for Heroku registry)
      - name: Build image
        run: docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web .

      # Push to Heroku registry
      - name: Push image
        run: docker push registry.heroku.com/${HEROKU_APP_NAME}/web

      # Release the pushed image
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: heroku container:release web -a ${HEROKU_APP_NAME}
